### ISSUE TITLE
Use native php libraries

### ISSUE THREAD

**Issue by Pierstoval** [PavelLoparev/design-patterns#1]
For observer or iterator, for instance,  you could use native SPL classes, what do you think ?

**Comment by PavelLoparev** [comment]
I just wanted to implement them manually. But I agree. I have should implement with predefined interfaces. I think I will do this in the nearest future. Thank you!

**Comment by PavelLoparev** [comment]
Ty

**Comment by PavelLoparev** [comment]
Committed
